name: Twitter PHP

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: mbstring, xdebug
        coverage: xdebug
    - name: Install dependencies
      working-directory: ./twitter-php
      run: |
        composer require --no-update --no-interaction "illuminate/support:${{ matrix.laravel-version }}"
        composer update --prefer-${{ matrix.stabilty }} --no-interaction --prefer-dist --no-suggest
    - name: Lint composer.json
      working-directory: ./twitter-php
      run: composer validate
    - name: Run Tests
      working-directory: ./twitter-php
      run: composer test:ci
      env:
        CI_TESTING: 'github-actions'
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: "${{secrets.CODECOV_TOKEN}}"
      working-directory: ./twitter-php
